[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = ["./gradlew clean bootJar -x test"]

[start]
cmd = "java -Xms96m -Xmx256m -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC -Dserver.port=$PORT -jar build/libs/collaborative-messenger-0.0.1-SNAPSHOT.jar"
